spring.datasource: # Database information
  platform: "mysql"
  url: "jdbc:mysql://localhost:3306/restaurant?useSSL=false"
  username: "user"
  password: "1234"
  testWhileIdle: true
  validationQuery: "SELECT 1"

spring.jpa: # JPA configuration
  hibernate.ddl-auto: "update"
  show-sql: true
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect